import { useState } from 'react'
import { Clock, CheckCircle2, AlertCircle, RefreshCw, Download, UserCheck } from 'lucide-react'

function getStatusBadge(status) {
  switch (status) {
    case 'Completed':
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-brand-success-light text-brand-success border border-brand-success/20 text-[10px] font-bold">
          <CheckCircle2 className="w-3 h-3" />
          Completed
        </span>
      )
    case 'Processing':
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-brand-info-light text-brand-info-dark border border-brand-info-border text-[10px] font-bold animate-pulse">
          <Clock className="w-3 h-3" />
          Processing
        </span>
      )
    case 'Failed':
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-brand-danger-light text-brand-danger border border-brand-danger-border text-[10px] font-bold">
          <AlertCircle className="w-3 h-3" />
          Failed
        </span>
      )
    default:
      return null
  }
}

export default function RecentExportHistoryTable({ history, onRedownload, onRetry }) {
  const [statusFilter, setStatusFilter] = useState('All')

  const filteredHistory = history.filter((h) => statusFilter === 'All' || h.status === statusFilter)

  return (
    <div className="bg-brand-surface border border-brand-border rounded-2xl p-5 shadow-xs hover:shadow-md hover:-translate-y-0.5 hover:border-brand-primary/40 transition-all duration-200 space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-brand-border/60 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-brand-info-light text-brand-info-dark">
            <Clock className="w-4 h-4" />
          </div>
          <h3 className="text-base font-bold text-brand-text">Recent Export History</h3>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-brand-text-muted">Status:</span>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-brand-bg-subtle border border-brand-border text-brand-text focus:outline-none"
          >
            <option value="All">All Statuses</option>
            <option value="Completed">Completed</option>
            <option value="Processing">Processing</option>
            <option value="Failed">Failed</option>
          </select>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs border-collapse">
          <thead>
            <tr className="border-b border-brand-border bg-brand-bg-subtle/70 text-brand-text-muted font-semibold uppercase tracking-wider">
              <th className="py-3 px-3">Date &amp; Time</th>
              <th className="py-3 px-3">Report Name</th>
              <th className="py-3 px-3">Generated By</th>
              <th className="py-3 px-3">Format</th>
              <th className="py-3 px-3">Status</th>
              <th className="py-3 px-3 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-brand-border/60">
            {filteredHistory.length === 0 ? (
              <tr>
                <td colSpan={6} className="py-8 text-center text-brand-text-subtle">
                  No export records yet — downloads you make will show up here.
                </td>
              </tr>
            ) : (
              filteredHistory.map((record) => (
                <tr key={record.id} className="hover:bg-brand-bg-subtle transition-colors">
                  <td className="py-3 px-3 whitespace-nowrap text-brand-text-muted font-medium">{record.dateTime}</td>

                  <td className="py-3 px-3 max-w-xs font-bold text-brand-text">
                    <div className="truncate">{record.reportName}</div>
                    <span className="text-[10px] text-brand-text-subtle font-normal">File Size: {record.fileSize}</span>
                  </td>

                  <td className="py-3 px-3 whitespace-nowrap text-brand-text">
                    <div className="flex items-center gap-1.5">
                      <UserCheck className="w-3.5 h-3.5 text-brand-text-subtle" />
                      <span>{record.generatedBy}</span>
                    </div>
                  </td>

                  <td className="py-3 px-3 whitespace-nowrap">
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-brand-bg-subtle text-brand-text font-bold text-[10px] uppercase">{record.format}</span>
                  </td>

                  <td className="py-3 px-3 whitespace-nowrap">{getStatusBadge(record.status)}</td>

                  <td className="py-3 px-3 whitespace-nowrap text-right">
                    {record.status === 'Completed' ? (
                      <button
                        onClick={() => onRedownload(record)}
                        className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-brand-success-light hover:bg-brand-success/20 text-brand-success font-semibold text-[11px] border border-brand-success/20 transition-colors"
                      >
                        <Download className="w-3 h-3" />
                        Re-download
                      </button>
                    ) : record.status === 'Failed' ? (
                      <button
                        onClick={() => onRetry(record)}
                        className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-brand-danger-light hover:bg-brand-danger/20 text-brand-danger font-semibold text-[11px] border border-brand-danger-border transition-colors"
                      >
                        <RefreshCw className="w-3 h-3" />
                        Retry
                      </button>
                    ) : (
                      <span className="text-[11px] text-brand-info font-medium">Compiling...</span>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
