import { supabase } from '../../lib/supabaseClient';

export interface LiveReportOutreach { id: string; title: string; programName: string; activityType: string; date: string; programDate: string; description: string; topicsCovered: string; topics: string[]; farmersAttended: number; farmersReached: number; village: string; district: string }
export interface LiveReportProduct { productName: string; unit: string; quantitySold: number; salesValue: number; sellingPrice: number; costPrice: number }
export interface LiveIndividualReport { ownerName: string; ownerContact: string; outreachRecords: LiveReportOutreach[]; reviewTrainingRecords: LiveReportOutreach[]; farmersCount: number; totalSalesValue: number; totalProcurementValue: number; totalOperatingExpenses: number; grossProfit: number; netProfit: number; totalBills: number; avgBillValue: number; productBreakdown: LiveReportProduct[]; photos: string[] }

export async function getLiveIndividualReport(ruralMartId: string, start?: string, end?: string): Promise<LiveIndividualReport> {
  let salesQuery = supabase.from('sales').select('id, total_amount, sale_date').eq('rural_mart_id', ruralMartId); let procurementQuery = supabase.from('procurement').select('cost, procurement_date').eq('rural_mart_id', ruralMartId); let expensesQuery = supabase.from('expenses').select('amount, expense_date').eq('rural_mart_id', ruralMartId); let outreachQuery = supabase.from('outreach_programs').select('*').eq('rural_mart_id', ruralMartId);
  if (start) { salesQuery = salesQuery.gte('sale_date', start); procurementQuery = procurementQuery.gte('procurement_date', start); expensesQuery = expensesQuery.gte('expense_date', start); outreachQuery = outreachQuery.gte('program_date', start); }
  if (end) { salesQuery = salesQuery.lte('sale_date', end); procurementQuery = procurementQuery.lte('procurement_date', end); expensesQuery = expensesQuery.lte('expense_date', end); outreachQuery = outreachQuery.lte('program_date', end); }
  const [martRes, salesRes, procurementRes, expensesRes, outreachRes, farmersRes, productsRes] = await Promise.all([supabase.from('rural_marts').select('entrepreneur_name, mobile_number, email').eq('id', ruralMartId).single(), salesQuery, procurementQuery, expensesQuery, outreachQuery, supabase.from('farmers').select('id', { count: 'exact', head: true }).eq('rural_mart_id', ruralMartId), supabase.from('products').select('id, name, unit, purchase_price, selling_price').eq('rural_mart_id', ruralMartId)]);
  for (const result of [martRes, salesRes, procurementRes, expensesRes, outreachRes, farmersRes, productsRes]) if (result.error) throw result.error;
  const sales = salesRes.data ?? []; const saleIds = sales.map((sale) => sale.id); const itemsRes = saleIds.length ? await supabase.from('sale_items').select('sale_id, product_id, quantity, unit_price_at_sale').in('sale_id', saleIds) : { data: [], error: null }; if (itemsRes.error) throw itemsRes.error;
  const products = productsRes.data ?? []; const productById = new Map(products.map((product) => [product.id, product])); const productMap = new Map<string, LiveReportProduct>();
  for (const item of itemsRes.data ?? []) { const product = productById.get(item.product_id); if (!product) continue; const existing = productMap.get(product.id) ?? { productName: product.name, unit: product.unit, quantitySold: 0, salesValue: 0, sellingPrice: Number(product.selling_price), costPrice: Number(product.purchase_price) }; existing.quantitySold += Number(item.quantity); existing.salesValue += Number(item.quantity) * Number(item.unit_price_at_sale); productMap.set(product.id, existing); }
  const outreachRecords = (outreachRes.data ?? []).map((row): LiveReportOutreach => ({ id: row.id, title: row.activity_type, programName: row.activity_type, activityType: row.activity_type, date: row.program_date, programDate: row.program_date, description: row.activity_brief || '', topicsCovered: Array.isArray(row.topics_covered) ? row.topics_covered.join(', ') : '', topics: row.topics_covered ?? [], farmersAttended: Number(row.reported_attendance_count) || 0, farmersReached: Number(row.reported_attendance_count) || 0, village: row.village || '', district: '' }));
  const totalSalesValue = sales.reduce((sum, row) => sum + Number(row.total_amount), 0); const totalProcurementValue = (procurementRes.data ?? []).reduce((sum, row) => sum + Number(row.cost), 0); const totalOperatingExpenses = (expensesRes.data ?? []).reduce((sum, row) => sum + Number(row.amount), 0);
  const mart = martRes.data!;
  return { ownerName: mart.entrepreneur_name, ownerContact: mart.mobile_number || mart.email, outreachRecords, reviewTrainingRecords: outreachRecords.filter((row) => /training|review|meeting/i.test(row.title)), farmersCount: farmersRes.count ?? 0, totalSalesValue, totalProcurementValue, totalOperatingExpenses, grossProfit: totalSalesValue - totalProcurementValue, netProfit: totalSalesValue - totalProcurementValue - totalOperatingExpenses, totalBills: sales.length, avgBillValue: sales.length ? Math.round(totalSalesValue / sales.length) : 0, productBreakdown: [...productMap.values()].sort((a, b) => b.salesValue - a.salesValue), photos: [] };
}
