import React, { useState } from 'react';
import {
  Clock,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Download,
  UserCheck,
  FileType,
  FileSpreadsheet,
  FileText,
} from 'lucide-react';
import { ExportHistoryRecord } from '../../../shared/types';

interface RecentExportHistoryTableProps {
  history: ExportHistoryRecord[];
  onRedownload: (record: ExportHistoryRecord) => void;
  onRetry: (record: ExportHistoryRecord) => void;
}

export const RecentExportHistoryTable: React.FC<RecentExportHistoryTableProps> = ({
  history,
  onRedownload,
  onRetry,
}) => {
  const [statusFilter, setStatusFilter] = useState<string>('All');

  const filteredHistory = history.filter((h) => {
    if (statusFilter === 'All') return true;
    return h.status === statusFilter;
  });

  const getStatusBadge = (status: ExportHistoryRecord['status']) => {
    switch (status) {
      case 'Completed':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-900/60 text-emerald-800 dark:text-emerald-200 border border-emerald-300/40 text-[10px] font-bold">
            <CheckCircle2 className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
            Completed
          </span>
        );
      case 'Processing':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-sky-100 dark:bg-sky-900/60 text-sky-800 dark:text-sky-200 border border-sky-300/40 text-[10px] font-bold animate-pulse">
            <Clock className="w-3 h-3 text-sky-600 dark:text-sky-400" />
            Processing
          </span>
        );
      case 'Failed':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-rose-100 dark:bg-rose-900/60 text-rose-800 dark:text-rose-200 border border-rose-300/40 text-[10px] font-bold">
            <AlertCircle className="w-3 h-3 text-rose-600 dark:text-rose-400" />
            Failed
          </span>
        );
    }
  };

  return (
    <div className="bg-white dark:bg-[#121E19] border border-[#DDE6E0] dark:border-[#1E3129] rounded-2xl p-5 shadow-xs hover:shadow-md hover:-translate-y-0.5 hover:border-[#174F3A]/40 dark:hover:border-[#A3E6C5]/40 transition-all duration-200 space-y-4">
      {/* Header & Status Filter */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-emerald-900/40 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-blue-100 dark:bg-blue-900/60 text-blue-700 dark:text-blue-300">
            <Clock className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Recent Export History
            </h3>
          </div>
        </div>

        {/* Status Filter Select */}
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium text-slate-500 dark:text-emerald-400">Status:</span>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-slate-50 dark:bg-emerald-900/40 border border-slate-200 dark:border-emerald-800/50 text-slate-800 dark:text-emerald-200 focus:outline-none"
          >
            <option value="All">All Statuses</option>
            <option value="Completed">Completed</option>
            <option value="Processing">Processing</option>
            <option value="Failed">Failed</option>
          </select>
        </div>
      </div>

      {/* Table Container */}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs border-collapse">
          <thead>
            <tr className="border-b border-slate-200 dark:border-emerald-800/40 bg-slate-50/70 dark:bg-emerald-900/30 text-slate-500 dark:text-emerald-300 font-semibold uppercase tracking-wider">
              <th className="py-3 px-3">Date & Time</th>
              <th className="py-3 px-3">Report Name</th>
              <th className="py-3 px-3">Generated By</th>
              <th className="py-3 px-3">Format</th>
              <th className="py-3 px-3">Status</th>
              <th className="py-3 px-3 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-emerald-900/30">
            {filteredHistory.length === 0 ? (
              <tr>
                <td colSpan={6} className="py-8 text-center text-slate-400 dark:text-emerald-400/60">
                  No export records match the current filter.
                </td>
              </tr>
            ) : (
              filteredHistory.map((record) => (
                <tr
                  key={record.id}
                  className="hover:bg-slate-50/80 dark:hover:bg-emerald-900/20 transition-colors"
                >
                  {/* Date & Time */}
                  <td className="py-3 px-3 whitespace-nowrap text-slate-600 dark:text-emerald-300 font-medium">
                    {record.dateTime}
                  </td>

                  {/* Report Name */}
                  <td className="py-3 px-3 max-w-xs font-bold text-slate-900 dark:text-slate-100">
                    <div className="truncate">{record.reportName}</div>
                    <span className="text-[10px] text-slate-400 dark:text-emerald-400/50 font-normal">
                      File Size: {record.fileSize}
                    </span>
                  </td>

                  {/* Generated By */}
                  <td className="py-3 px-3 whitespace-nowrap text-slate-700 dark:text-emerald-200">
                    <div className="flex items-center gap-1.5">
                      <UserCheck className="w-3.5 h-3.5 text-slate-400 dark:text-emerald-400/70" />
                      <span>{record.generatedBy}</span>
                    </div>
                  </td>

                  {/* Format */}
                  <td className="py-3 px-3 whitespace-nowrap">
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-slate-100 dark:bg-emerald-900/50 text-slate-800 dark:text-emerald-200 font-bold text-[10px] uppercase">
                      {record.format}
                    </span>
                  </td>

                  {/* Status */}
                  <td className="py-3 px-3 whitespace-nowrap">
                    {getStatusBadge(record.status)}
                  </td>

                  {/* Action */}
                  <td className="py-3 px-3 whitespace-nowrap text-right">
                    {record.status === 'Completed' ? (
                      <button
                        onClick={() => onRedownload(record)}
                        className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-emerald-50 dark:bg-emerald-900/40 hover:bg-emerald-100 dark:hover:bg-emerald-800/60 text-emerald-700 dark:text-emerald-300 font-semibold text-[11px] border border-emerald-200 dark:border-emerald-700/50 transition-colors"
                      >
                        <Download className="w-3 h-3" />
                        Re-download
                      </button>
                    ) : record.status === 'Failed' ? (
                      <button
                        onClick={() => onRetry(record)}
                        className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-rose-50 dark:bg-rose-900/40 hover:bg-rose-100 dark:hover:bg-rose-800/60 text-rose-700 dark:text-rose-300 font-semibold text-[11px] border border-rose-200 dark:border-rose-700/50 transition-colors"
                      >
                        <RefreshCw className="w-3 h-3" />
                        Retry
                      </button>
                    ) : (
                      <span className="text-[11px] text-sky-600 dark:text-sky-400 font-medium">
                        Compiling...
                      </span>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};
